### Variable para la URL base
@baseUrl = http://localhost:3000/api/trajes

### Prueba 1: Crear un nuevo Traje
POST {{baseUrl}}
Content-Type: application/json

{
  "codigoEtiqueta": "SMOK-005",
  "talle": "35",
  "color": "Rojo",
  "categoria": "Smoking",
  "precioAlquilerBase": 26000.00
}

### Prueba 2: Obtener todos los trajes
GET {{baseUrl}}