### Crear Cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJSb21hbiIsImlhdCI6MTc3NTA4NTIxNCwiZXhwIjoxNzc1MDk5NjE0fQ.Vx8nE1Z87sOWgw7fh8pzgqhFFUImtsIiwgpjCZkdh_0

{
    "nombre": "Pablo Perez",
    "dni": "20548975",
    "telefono": "28895123456",
    "email": "pablo@correo.com"
}

### Obtener Clientes
GET http://localhost:3000/api/clientes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJSb21hbiIsImlhdCI6MTc3NTA1MTM1MCwiZXhwIjoxNzc1MDY1NzUwfQ.fZkNOHgHsFvLbrcwMrbkJM4XNMsVkI7dLLOGNH1KIG4